package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class DiceGameScene {
	@FXML
	private TextField yourBetTF;
	@FXML
	private Label yourPointLabel;
	@FXML
	private Label botBetLabel;
	@FXML
	private Label botPointsLabel;
	@FXML
	private Label diceRollLabel;

	// Event Listener on Button.onAction
	@FXML
	public void loadGameScene(ActionEvent event) {
		ViewNavigator.loadScene("Game Scene", ViewNavigator.GAME_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void playDiceGame(ActionEvent event) {
		// TODO Autogenerated
	}
}
