package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ForgotAccountScene {
	@FXML
	private TextField emailTF;
	@FXML
	private Label iDLabel;
	@FXML
	private Label passwordLabel;
	@FXML
	private Label emailErrorlabel;
	@FXML
	private Label wrongEmailErrorLabel;

	// Event Listener on Button.onAction
	@FXML
	public void giveAccountInfo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadSignIn(ActionEvent event) {
		ViewNavigator.loadScene("Sign In", ViewNavigator.SIGN_IN_SCENE);
	}
}
