package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.RadioButton;

public class GameQuizEasyScene implements Initializable {
	@FXML
	private Label GameQuizEasyQuestionLabel;
	@FXML
	private RadioButton rbA;
	@FXML
	private RadioButton rbB;
	@FXML
	private RadioButton rbD;
	@FXML
	private RadioButton rbC;

	// Event Listener on Button.onAction
	@FXML
	public void loadGameQuizScene(ActionEvent event) {
		ViewNavigator.loadScene("GAME QUIZ",ViewNavigator.GAME_QUIZ_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadNextGameQuizEasy(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
