package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.cs272.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class GuessingGameScene implements Initializable{
    private static Controller controller = Controller.getInstance();

	@FXML
	private Label GGQuestionLabel;
	@FXML
	private Label choiceALabel;
	@FXML
	private Label choiceBLabel;
	@FXML
	private Label choiceCLabel;
	@FXML
	private Label choiceDLabel;

	// Event Listener on Button.onAction
	@FXML
	public void loadGameScene(ActionEvent event) {
	    ViewNavigator.loadScene("Game List", ViewNavigator.GAME_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadNextQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void checkAnswerA(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void checkAnswerB(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void checkAnswerC(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void checkAnswerD(ActionEvent event) {
		// TODO Autogenerated
	}
    @Override
    public void initialize(URL arg0, ResourceBundle arg1)
    {
        GGQuestionLabel.setText(controller.getQuestion());

    }
}
