package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class MathScene {
	@FXML
	private Button easyBT;
	@FXML
	private Button hardBT;
	@FXML
	private Button extremelyBT;
	@FXML
	private Button backBT;
	@FXML
	private Label mathLevelLabel;

	// Event Listener on Button[#backBT].onAction
	@FXML
	public void loadQuizScene(ActionEvent event) {
		// TODO Autogenerated
	}
}
