package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class QuizScene {
	@FXML
	private Button gamesQuizBT;
	@FXML
	private Button mathQuizBT;
	@FXML
	private Button randomQuizBT;
	@FXML
	private Button backBT;
	@FXML
	private Label WTQGLabel;

	// Event Listener on Button[#gamesQuizBT].onAction
	@FXML
	public void loadGameQuiz(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#mathQuizBT].onAction
	@FXML
	public void loadMathQuiz(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#randomQuizBT].onAction
	@FXML
	public void loadRandomQuiz(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#backBT].onAction
	@FXML
	public void loadMainMenu(ActionEvent event) {
	    ViewNavigator.loadScene("Main Menu", ViewNavigator.MAIN_MENU);
	}
}
