package edu.orangecoastcollege.cs272.view;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.cs272.controller.Controller;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

public class RandomQuizScene implements Initializable{
    private static Controller controller = Controller.getInstance();

	@FXML
	private Label RDQuestionLabel;
	@FXML
	private Button choiceABT;
	@FXML
	private Button choiceBBT;
	@FXML
	private Button choiceCBT;
	@FXML
	private Button choiceDBT;

	// Event Listener on Button.onAction
	@FXML
	public void loadGameScene(ActionEvent event) {
	    ViewNavigator.loadScene("Game List", ViewNavigator.GAME_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadNextQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#choiceABT].onAction
	@FXML
	public void checkAnswerA(ActionEvent event) {
	//	if(controller.checkAnswer(choiceABT.getText()) == false)
		///    ViewNavigator.loadScene("Congratulation", ViewNavigator.WIN_GUESSING_GAME_SCENE);
	}
	// Event Listener on Button[#choiceBBT].onAction
	@FXML
	public void checkAnswerB(ActionEvent event) {
	  //  if(controller.checkAnswer(choiceABT.getText()) == true)
       //     ViewNavigator.loadScene("Congratulation", ViewNavigator.WIN_GUESSING_GAME_SCENE);
	    }
	// Event Listener on Button[#choiceCBT].onAction
	@FXML
	public void checkAnswerC(ActionEvent event) {
	   // if(controller.checkAnswer(choiceABT.getText()) == true)
       //     ViewNavigator.loadScene("Congratulation", ViewNavigator.WIN_GUESSING_GAME_SCENE);
	    }
	// Event Listener on Button[#choiceDBT].onAction
	@FXML
	public void checkAnswerD(ActionEvent event) {
	  //  if(controller.checkAnswer(choiceABT.getText()) == true)
       //     ViewNavigator.loadScene("Congratulation", ViewNavigator.WIN_GUESSING_GAME_SCENE);
	    }
    @Override
    public void initialize(URL arg0, ResourceBundle arg1)
    {
        RDQuestionLabel.setText(controller.getRandomQuestion()[0]);
        choiceABT.setText(controller.getRandomQuestion()[1]);
        choiceBBT.setText(controller.getRandomQuestion()[2]);
        choiceCBT.setText(controller.getRandomQuestion()[3]);
        choiceDBT.setText(controller.getRandomQuestion()[4]);
    }
}
