package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.RadioButton;

public class RandomQuizScene {
	@FXML
	private Label RandomQuestionLabel;
	@FXML
	private RadioButton rbA;
	@FXML
	private RadioButton rbB;
	@FXML
	private RadioButton rbD;
	@FXML
	private RadioButton rbC;

	// Event Listener on Button.onAction
	@FXML
	public void loadQuizScene(ActionEvent event) {
		ViewNavigator.loadScene("Game", ViewNavigator.QUIZ_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadNextRandomQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
}
