package edu.orangecoastcollege.cs272.view;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class UsernameScene {

	// Event Listener on Button.onAction
	@FXML
	public void loadAccountScene(ActionEvent event) {
		// TODO Autogenerated
	}
}
